#!/bin/bash

make link

# Install Nix
if command -v nix-env >/dev/null 2>&1; then
    echo "✅ Nix is already installed"
else
    echo "📦 Installing Nix..."
    if ! sh <(curl -L https://nixos.org/nix/install) --no-daemon; then
        echo "❌ Nix installation failed!"
        exit 1
    fi
    echo "✅ Nix Installed!"
fi

# Source Nix profile
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
    . "$HOME/.nix-profile/etc/profile.d/nix.sh"
else
    echo "❌ Nix profile not found. Installation may have failed."
    exit 1
fi

# Configure Nix
echo "📦 Configuring Nix..."
mkdir -p ~/.config/nix
echo 'experimental-features = nix-command flakes' >~/.config/nix/nix.conf

# Install Home Manager
echo "📦 Installing Home Manager..."
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
nix-shell '<home-manager>' -A install
# home-manager switch --flake .#profile --verbose -b bckp
echo "🎉 Installation Complete! You can use $(shell chsh -s /bin/fish)."
