# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b5076ba0-5f3a-406e-b3f8-09f6d5b3b94d";
    fsType = "btrfs";
    options = ["subvol=@root"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E7F3-ADAF";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b5076ba0-5f3a-406e-b3f8-09f6d5b3b94d";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/b5076ba0-5f3a-406e-b3f8-09f6d5b3b94d";
    fsType = "btrfs";
    options = ["subvol=@var"];
  };

  swapDevices = [{device = "/dev/disk/by-uuid/73f22df8-6b39-4740-84b4-89251ad3542f";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
